modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="backitems" #mandatory
version="${version}" #mandatory
displayName="Back Items" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="KeyCrusader" #optional
description='''
Adds several items to be used in a back slot with the Curios API
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.backitems]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.backitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.backitems]] #optional
    modId="curios" #mandatory
    mandatory=false #mandatory
    versionRange="[2.0,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.backitems]] #optional
    modId="caelus" #mandatory
    mandatory=false #mandatory
    versionRange="[2.0,)" #mandatory
    ordering="BEFORE"
    side="BOTH"

