modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/KeyCrusader/BackItems/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="${mod_url}" #optional
logoFile="${mod_icon}" #optional
authors="${mod_author}" #optional
description='''
${mod_description}
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.backitems]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.backitems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.backitems]] #optional
    modId="curios" #mandatory
    mandatory=true #mandatory
    versionRange="FORGE-1.15.2-2.0.2.4,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.backitems]] #optional
    modId="caelus" #mandatory
    mandatory=true #mandatory
    versionRange="[FORGE-1.15.2-2.0-beta3,)" #mandatory
    ordering="BEFORE"
    side="BOTH"

